# Data Preprocessing of images. Resizing all images to 100*100 and gray scaling

In [38]:
import cv2
import os

data_path='dataset'
categories=os.listdir(data_path)
labels=[i for i in range(len(categories))]

label_dict=dict(zip(categories,labels)) #empty dictionary

print(label_dict)
print(categories)
print(labels)

{'with mask': 0, 'without mask': 1}
['with mask', 'without mask']
[0, 1]


In [15]:
for files in categories:
    print(files)

with mask
without mask


In [13]:
pwd

'C:\\Users\\Keerti\\pythonProject1\\face-mask-detection-keras'

In [8]:
pip install opencv-python

  Using cached opencv_python-4.5.1.48-cp37-cp37m-win_amd64.whl (34.9 MB)
  Using cached numpy-1.20.1-cp37-cp37m-win_amd64.whl (13.6 MB)
Note: you may need to restart the kernel to use updated packages.


In [17]:
img_size=100
data=[]
target=[]


for category in categories:
    folder_path=os.path.join(data_path,category)
    img_names=os.listdir(folder_path)
        
    for img_name in img_names:
        img_path=os.path.join(folder_path,img_name)
        img=cv2.imread(img_path)

        try:
            gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)           
            #Coverting the image into gray scale
            resized=cv2.resize(gray,(img_size,img_size))
            #resizing the gray scale into 50x50, since we need a fixed common size for all the images in the dataset
            data.append(resized)
            target.append(label_dict[category])
            #appending the image and the label(categorized) into the list (dataset)

        except Exception as e:
            print('Exception:',e)
            #if any exception rasied, the exception will be printed here. And pass to the next image

In [18]:
data

[array([[51, 52, 64, ..., 85,  9, 33],
        [51, 55, 62, ..., 20, 60, 40],
        [54, 52, 48, ..., 71, 52,  4],
        ...,
        [74, 77, 70, ..., 14,  5, 51],
        [64, 68, 74, ...,  5, 12,  9],
        [60, 60, 56, ..., 15, 15, 15]], dtype=uint8),
 array([[250, 250, 251, ..., 251, 251, 251],
        [250, 250, 251, ..., 251, 251, 251],
        [251, 251, 251, ..., 252, 252, 252],
        ...,
        [255, 255, 255, ...,  23,  21,  22],
        [255, 255, 255, ...,  22,  21,  22],
        [255, 255, 255, ...,  21,  21,  22]], dtype=uint8),
 array([[223, 225, 226, ..., 200, 195, 190],
        [226, 227, 229, ..., 204, 198, 195],
        [228, 229, 230, ..., 206, 202, 198],
        ...,
        [200, 206, 199, ...,  40,  40,  29],
        [174, 188, 197, ...,  43,  33,  30],
        [162, 178, 186, ...,  37,  28,  26]], dtype=uint8),
 array([[255, 255, 255, ..., 254, 254, 254],
        [255, 255, 255, ..., 254, 254, 254],
        [255, 254, 252, ..., 225, 215, 208],
       

In [32]:
pip install tensorflow --ignore-installed


  Using cached tensorflow-2.4.1-cp37-cp37m-win_amd64.whl (370.7 MB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
  Using cached wrapt-1.12.1-py3-none-any.whl
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
  Using cached tensorboard-2.4.1-py3-none-any.whl (10.6 MB)
  Using cached tensorflow_estimator-2.4.0-py2.py3-none-any.whl (462 kB)
  Using cached grpcio-1.32.0-cp37-cp37m-win_amd64.whl (2.5 MB)
  Using cached h5py-2.10.0-cp37-cp37m-win_amd64.whl (2.5 MB)
  Using cached numpy-1.19.5-cp37-cp37m-win_amd64.whl (13.2 MB)
  Using cached protobuf-3.14.0-cp37-cp37m-win_amd64.whl (798 kB)
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
  Using cached absl_py-0.11.0-py3-none-any.whl (127 kB)
  Using cached Keras_Preprocessing-1.1.2-

In [33]:
import numpy as np

data=np.array(data)/255.0
data=np.reshape(data,(data.shape[0],img_size,img_size,1))
target=np.array(target)

from keras.utils import np_utils

new_target=np_utils.to_categorical(target)

Using TensorFlow backend.


In [36]:
new_target

array([0, 0, 0, ..., 1, 1, 1])

In [37]:
np.save('data',data)
np.save('target',new_target)